In [60]:
import numpy as np
import pandas as pd

In [61]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [62]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [63]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [64]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [65]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# working with dates

In [66]:
date['date'] = pd.to_datetime(date['date'])

In [67]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. extract year

In [68]:
date['date_year'] = date['date'].dt.year

In [69]:
date.sample(5)

          date  product_id  city_id  orders  date_year
210 2018-10-13        3403        1      15       2018
138 2019-06-04        4635       22      12       2019
421 2019-07-05        5970       26       1       2019
348 2019-02-09        1848       14     135       2019
586 2019-06-26        2563       18       8       2019

2. Extract month

In [70]:
date['date_month_no'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
723 2018-12-07        2879        3       1       2018             12
572 2019-07-03        4191       16       3       2019              7
379 2019-10-11        2381       18      23       2019             10
294 2018-12-02        3601        9       1       2018             12
739 2019-08-06        1673       13       2       2019              8

In [71]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
15,2019-02-14,202,2,4,2019,2,February
724,2019-06-16,2415,22,1,2019,6,June
492,2019-06-24,2306,14,12,2019,6,June
786,2018-08-21,888,20,6,2018,8,August
46,2018-09-23,2815,13,1,2018,9,September

3. Extract date

In [72]:
date['date_now'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [73]:
# day of week
date['date_DoW'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now,date_DoW
86,2019-06-27,3904,1,29,2019,6,June,27,3
32,2018-10-23,2845,23,1,2018,10,October,23,1
708,2019-06-05,5004,25,5,2019,6,June,5,2
814,2019-06-13,6438,24,8,2019,6,June,13,3
807,2019-11-17,7367,22,1,2019,11,November,17,6

In [74]:
# name of day
date['date_DoW_name'] = date['date'].dt.day_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now,date_DoW,date_DoW_name
668,2019-11-01,6937,13,38,2019,11,November,1,4,Friday
516,2018-12-09,3953,13,1,2018,12,December,9,6,Sunday
346,2018-11-10,2215,16,1,2018,11,November,10,5,Saturday
430,2019-10-20,6336,23,13,2019,10,October,20,6,Sunday
24,2019-07-24,2303,14,113,2019,7,July,24,2,Wednesday

In [75]:
# is weekend?
date['date_is_weekend'] = date['date_DoW_name'].isin(['Sunday','Saterday']).astype('int')

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now,date_DoW,date_DoW_name,date_is_weekend
768,2018-12-30,4990,1,2,2018,12,December,30,6,Sunday,1
256,2019-07-28,4814,14,1,2019,7,July,28,6,Sunday,1
488,2019-10-30,6663,4,1,2019,10,October,30,2,Wednesday,0
422,2019-11-24,6717,3,1,2019,11,November,24,6,Sunday,1
884,2019-04-03,5314,11,7,2019,4,April,3,2,Wednesday,0

Extract week of the year

In [77]:
date['date_week'] = date['date'].dt.isocalendar().week
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now,date_DoW,date_DoW_name,date_is_weekend,date_week
298,2018-12-12,3748,17,11,2018,12,December,12,2,Wednesday,0,50
996,2018-12-06,5521,7,1,2018,12,December,6,3,Thursday,0,49
635,2018-11-11,6295,3,84,2018,11,November,11,6,Sunday,1,45
766,2018-07-13,3454,14,8,2018,7,July,13,4,Friday,0,28
904,2019-06-17,1828,0,1,2019,6,June,17,0,Monday,0,25

In [81]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now,date_DoW,date_DoW_name,date_is_weekend,date_week
383,2019-11-28,820,30,6,2019,11,November,28,3,Thursday,0,48
77,2018-11-02,5905,30,1,2018,11,November,2,4,Friday,0,44
570,2018-12-18,2687,25,31,2018,12,December,18,1,Tuesday,0,51
212,2019-10-11,3340,9,1,2019,10,October,11,4,Friday,0,41
537,2019-06-29,2563,18,14,2019,6,June,29,5,Saturday,0,26

 Extract Quarter

In [82]:
date['Quarter'] = date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now,date_DoW,date_DoW_name,date_is_weekend,date_week,Quarter
9,2018-08-30,4373,11,3,2018,8,August,30,3,Thursday,0,35,3
690,2018-12-16,3799,20,3,2018,12,December,16,6,Sunday,1,50,4
709,2018-11-21,3916,27,2,2018,11,November,21,2,Wednesday,0,47,4
814,2019-06-13,6438,24,8,2019,6,June,13,3,Thursday,0,24,2
551,2019-06-27,6756,17,2,2019,6,June,27,3,Thursday,0,26,2

In [83]:
# Extract Semester
date['Semester'] = np.where(date['Quarter'].isin([1,2]), 1, 2)
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_now,date_DoW,date_DoW_name,date_is_weekend,date_week,Quarter,Semester
452,2018-11-05,7450,21,4,2018,11,November,5,0,Monday,0,45,4,2
719,2018-11-14,5965,13,10,2018,11,November,14,2,Wednesday,0,46,4,2
420,2018-08-07,7288,14,5,2018,8,August,7,1,Tuesday,0,32,3,2
594,2019-04-14,547,4,86,2019,4,April,14,6,Sunday,1,15,2,1
956,2018-07-20,7334,21,9,2018,7,July,20,4,Friday,0,29,3,2

Extract Time elasped between dates

In [84]:
import datetime 
today = datetime.datetime.now()

today

datetime.datetime(2026, 1, 25, 11, 21, 44, 24526)

In [85]:
today - date['date']

0     2238 days 11:21:44.024526
1     2720 days 11:21:44.024526
2     2651 days 11:21:44.024526
3     2353 days 11:21:44.024526
4     2576 days 11:21:44.024526
                 ...
995   2666 days 11:21:44.024526
996   2607 days 11:21:44.024526
997   2455 days 11:21:44.024526
998   2520 days 11:21:44.024526
999   2294 days 11:21:44.024526
Name: date, Length: 1000, dtype: timedelta64[ns]

In [86]:
(today - date['date']).dt.days

0      2238
1      2720
2      2651
3      2353
4      2576
       ...
995    2666
996    2607
997    2455
998    2520
999    2294
Name: date, Length: 1000, dtype: int64

In [87]:
# months passed
np.round((today - date['date']).dt.days / 30)

0      75.0
1      91.0
2      88.0
3      78.0
4      86.0
       ...
995    89.0
996    87.0
997    82.0
998    84.0
999    76.0
Name: date, Length: 1000, dtype: float64

# Working with Time

In [88]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [89]:
time['date'] = pd.to_datetime(time['date'])

In [90]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [91]:

time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [92]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [93]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [94]:
time['date'] = time['date'].dt.date

In [95]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00